### PR TITLE
oauth2-server: fixed rule patterns

### PR DESCRIPTION
**Pull request by KrasimirRaikov**
fixed rule patterns of jackson in jarjar plugin

### CODE REVIEW

**Comment by KrasimirRaikov** [comment]
@mgenov the rule patterns were mistaken and were making trouble when trying to use jackson library.
I fixed them, but then it turned out that the jarjar wasn't needed. If you need it for some reason I can just fix the patterns

**Comment by mgenov** [comment]
It's required by the jjwt library as it's transient dependent. 

e.g  oauth2-server -> jjwt -> jackson 

You can verify it by try to use the jjwt functionality.

**Comment by mgenov** [comment]
By jarjaring jackson we are not forcing client apps which are using the library to include and whole jackson lib.

**Comment by KrasimirRaikov** [comment]
I have returned the jarjar plugin and have fixed the rule patterns, also the result packaging

**Review by mgenov — APPROVED** [review]
LGTM !

**Comment by KrasimirRaikov** [comment]
@mgenov could you update the oauth2 in the sonatype repository, because I have changes which depend on the jackson library in accounts, and right now their is a problem with the dependency

**Comment by mgenov** [comment]
v1.0.1 is released and is available in the sonatype repository: https://oss.sonatype.org/content/repositories/releases/com/clouway/security/oauth2-server/1.0.1/

**Pull request merged**
