### PR TITLE
oauth-server: custom params are passed from authorization object

### PR DESCRIPTION
**Pull request by qnislavnachev**
Custom params currently were passed to the callback url but now they are passed from the authorization request.

### CODE REVIEW

**Comment by mgenov** [comment]
Do I have to review this PR or someone will take care on this one ?

**Review by mgenov — APPROVED** [review]
LGTM !

**Comment by qnislavnachev** [comment]
@mgenov  This PR was reviewed by @mlesikov  and @VasilMitovClouway, but they were waiting for some testing to be done.

**Comment by mgenov** [comment]
Version 1.0.4 is released.

**Comment by qnislavnachev** [comment]
Thanks @mgenov, can you give me information about ``` oauth2-java-client ``` is it released with last changes ?

**Comment by mgenov** [comment]
There is a release from 5'th feb: https://oss.sonatype.org/content/repositories/releases/com/clouway/security/oauth2-java-client-console/0.0.2/

**Comment by qnislavnachev** [comment]
Thanks

**Pull request merged**
