### PR TITLE
oauth2-server/id_token: id_token now returned with JWT

### PR DESCRIPTION
**Pull request by VasilMitovClouway**
Now id_token is returned when JWT token is issued to save a round-trip in app to app communication. 

Fixes: #43

### CODE REVIEW

**Comment by mgenov** [comment]
This looks same as previous PR. Why there are 2 for this one ?

**Comment by VasilMitovClouway** [comment]
The first PR was the id token to be returned for the refresh_token. This is for the JWT token controller.
I just did the two PRs separate. Am i missing something ?

**Comment by mgenov** [comment]
Yes, the same behaviour looks duplicated between all flows, e.g issuing new token, refreshing of existing token and issuing of new jwt token.

**Review by mgenov — APPROVED** [review]
LGTM !

**Pull request merged**
